// <auto-generated />
namespace WebInstruments.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class insert_Cidades : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(insert_Cidades));
        
        string IMigrationMetadata.Id
        {
            get { return "201611131118090_insert_Cidades"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
