DELETE FROM State;
INSERT INTO State (Acronym, Name) VALUES('PR','Paraná');
INSERT INTO State (Acronym, Name) VALUES('AC','Acre');  
INSERT INTO State (Acronym, Name) VALUES('AL','Alagoas');  
INSERT INTO State (Acronym, Name) VALUES('AM','Amazonas');
INSERT INTO State (Acronym, Name) VALUES('AP','Amapá');
INSERT INTO State (Acronym, Name) VALUES('BA','Bahia');
INSERT INTO State (Acronym, Name) VALUES('CE','Ceará');
INSERT INTO State (Acronym, Name) VALUES('DF','Distrito Federal');
INSERT INTO State (Acronym, Name) VALUES('ES','Espírito Santo');
INSERT INTO State (Acronym, Name) VALUES('GO','Goiás');
INSERT INTO State (Acronym, Name) VALUES('MA','Maranhão');
INSERT INTO State (Acronym, Name) VALUES('MG','Minas Gerais');
INSERT INTO State (Acronym, Name) VALUES('MS','Mato Grosso do Sul');
INSERT INTO State (Acronym, Name) VALUES('MT','Mato Grosso');
INSERT INTO State (Acronym, Name) VALUES('PA','Pará');
INSERT INTO State (Acronym, Name) VALUES('PB','Paraíba');
INSERT INTO State (Acronym, Name) VALUES('PE','Pernambuco');
INSERT INTO State (Acronym, Name) VALUES('PI','Piauí');
INSERT INTO State (Acronym, Name) VALUES('RJ','Rio de Janeiro');
INSERT INTO State (Acronym, Name) VALUES('RN','Rio Grande do Norte');
INSERT INTO State (Acronym, Name) VALUES('RO','Rondônia');
INSERT INTO State (Acronym, Name) VALUES('RR','Roraima');
INSERT INTO State (Acronym, Name) VALUES('RS','Rio Grande do Sul');
INSERT INTO State (Acronym, Name) VALUES('SC','Santa Catarina');
INSERT INTO State (Acronym, Name) VALUES('SE','Sergipe');
INSERT INTO State (Acronym, Name) VALUES('SP','São Paulo');
INSERT INTO State (Acronym, Name) VALUES('TO','Tocantins');