INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Centímetro', 'cm');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Metro', 'm');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Celcius', 'Cº');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Metro quadrado', 'm²');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Watt', 'W');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Segundo', 's');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Farenheit', 'Fº');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Newton', 'N');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Hertz', 'Hz');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('radiano', 'rad');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Hertz', 'Hz');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Joule', 'J');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Coloumb', 'C');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Volt', 'V');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Ohm', 'Ώ');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Farad', 'F');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Tesla', 'T');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('kelvin', 'K');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Ampére', 'A');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('mol', 'mol');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Quilo por metro cúbico', 'Kg/m³');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Quilo', 'Kg');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Grama', 'g');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Miligrama', 'mg');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Minuto', 'min');
INSERT INTO MeasurementUnit(Name, Acronym) VALUES('Tonelada', 'T');